### ISSUE TITLE
Adopt latest version of OpenRewrite

### ISSUE THREAD

**Issue by timtebeek** [testcontainers/rewrite-testcontainers#1]
As discussed, I propose we upgrade this project to use the latest version of OpenRewrite, and adopt a few changes along the way. Here's a rough list of tasks off the top of my head; welcome to add more or branch them off into separate issues.

### Tasks
- [ ] Replace the current Kotlin tests with Java
- [ ] Update README to support Testcontainer migrations
- [ ] Override `getDescription()` and `getEstimatedEffortPerOccurrence()`
- [ ] Add Testcontainer specific release workflow
- [ ] Add Dependabot, Renovate or OpenRewrite to keep up with new dependency versions, preferably merged automatically.
- [ ] Bump Gradle wrapper from 7.4.2 to 7.6.1
- [ ] Add recipe to add `@TestContainers(parallel = true)`
- [ ] Add recipes to migrate to new JUnit-free API

**Comment by kiview** [comment]
Hey @timtebeek , thanks for opening this issues, sounds good to me. Did you discuss this already in more detail with @eddumelendez?

**Comment by timtebeek** [comment]
Hi @kiview ! Eddu and I chatted a while ago, but haven't folllowed up since; this list was a quick write up of our discussion at the time. I've added a few more items to the list just now, based on what I gathered from [this comment](https://github.com/testcontainers/testcontainers-java/pull/5826#issuecomment-1504314386) and the recent release notes. Happy to discuss some more, and see where we can help facilitate these changes.

**Comment by timtebeek** [comment]
Hi all! With OpenRewrite 8.0 around the corner there's potentially some more changes that need to be made to these recipes to get them working with the latest versions again. In light of this and future changes, we propose to pull this repository into the OpenRewrite GitHub organization, such that it's easier for us to help maintain going forward. That also enables us to leverage some of our existing automations around upgrades and releases, for a smoother experience in developing and using these recipes. Would you all be open to such a change?

In short the steps to migrate recipes to the OpenRewrite organization come down to:

1. Transfer this repository to the [OpenRewrite organization](https://github.com/openrewrite/) in GitHub.
2. Provide us with a list of GitHub usernames that should be granted access.
3. (**Optionally**) After the first release in this new repository, link your original repository to both this new repository and the auto-generated documentation for your recipes so that people can find and learn about them.

**We then guarantee to:**

1. Keep your repository up to date with changes in OpenRewrite
2. Document your recipes on [https://docs.openrewrite.org](https://docs.openrewrite.org)
3. Periodically release new versions of your recipes

**We ask that you:**

1. Help answer questions specific to your project
2. Help review and develop new recipes for your project

We understand that this model might not suit all teams and organizations. If this doesn't suit your's, we will still try and help ensure that your recipes continue working. Please [keep an eye out for](https://github.com/openrewrite/rewrite/releases) our 8.0 release and the instructions that will come with that. Also, feel free to [ask questions in any of our support channels](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#asking-questions--reporting-issues).

**Comment by eddumelendez** [comment]
Sorry for the late reply, @timtebeek ! 

> Would you all be open to such a change?

The plan totally make sense 👍🏽

> Provide us with a list of GitHub usernames that should be granted access.

I think currently it's just me.

IIRC I should be an organization member first before doing the transfer but that's an issue with org permissions. I can give it a try, tho.

**Comment by timtebeek** [comment]
Hi @eddumelendez ! No problem at all; let's see how we can get this started. With rewrite-jenkins just the other week we worked out that the owner can initiate a transfer either to the openrewrite organization, or me as an intermediary. GitHub should take care of any redirect, even if I then have to transfer from my account to OpenRewrite I believe.

The only thing you might want to check on your end is that there are no secrets associated with the project specifically. Organization secrets aren't transferred as far as I know, but it doesn't hurt to check.

Welcome to start the transfer on your end, or we can plan a moment to do this together. I'm on CET, but available at odd hours.

Then the next step would be an issue such as this one to [list of the adoption steps](https://github.com/openrewrite/rewrite-jenkins/issues/4), in addition to what we have above.

**Comment by timtebeek** [comment]
As discussed, rather than fix the build issues here and maintain these separately, we've decided to move these recipes into rewrite-testing-frameworks:
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/433
